### PR TITLE
Build the documentation using sphinx, for hosting on readthedocs

### PR DESCRIPTION
**Pull request by traverseda**
Applies a nice template and search to the documents, it looks like [this](https://docs.readthedocs.io/en/latest/getting_started.html)

You can build this documentation yourself with

```
pip install --user sphinx recommonmark sphinx_rtd_theme
cd doc
make html
```

If you register for a readthedocs.org account, it will build and host the docs automatically. Alternatively, you can host using github pages and just build manually.

### CODE REVIEW

**Comment by vygr** [comment]
Hi Alex, so do I only need the doc/Makefile to let people build there own readTheDocs docs ? The rest of the changes seam to be a set of the generated docs ? Is that correct ?

Chris

**Comment by traverseda** [comment]
I probably should have done it in two commits, but yeah. The `conf.py`, `make.bat`,  and `Makefile` are the only files I added. The `_` directories are all auto generated.

The commands I included in the commit message are all you need to build the docs on a linux system with python installed. You use pip to install sphinx, which the makefile uses to build the HTML.

**Comment by vygr** [comment]
Thanks Alex ! The files for creating Sphinx docs have been merged into master.

Chris

**Comment by baydrift** [comment]
Hi Chris,
I saw that too on Ubuntu.
"make Makefile html"
seemed to work without errors.
Andy

**Comment by vygr** [comment]
I'll give that a try...

I also got the same issue on my Ubuntu VM.

Chris

**Comment by vygr** [comment]
Doesn't help on Mac. Trying Ubuntu now...

**Comment by traverseda** [comment]
> And then the index.html dosn't give me anything that links to other pages. 

The solutions to that is to make an "index.md" that links to them, unless you want to get more complicated with auto-generating an index, but I think simple is fine for now.

I think your errors come from not having the "readthedocs" theme, and not having the markdown rendering library it uses. You can still both (on linux, I'm not sure about mac) using

    pip install --user sphinx recommonmark sphinx_rtd_theme

**Comment by vygr** [comment]
Nope Ubuntu still gives no index.html that leads anywhere.

Output from 'make Makefie html'

chris@chris-VirtualBox-17:~/Documents/ChrysaLisp/doc$ make Makefile html
make: Nothing to be done for 'Makefile'.
Running Sphinx v1.7.2
making output directory...
loading pickled environment... not yet created
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 5 source files that are out of date
updating environment: 5 added, 0 changed, 0 removed
reading sources... [100%] index                                                 
looking for now-outdated files... none found
pickling environment... done
checking consistency... /home/chris/Documents/ChrysaLisp/doc/FUNCTIONS.md: WARNING: document isn't included in any toctree
/home/chris/Documents/ChrysaLisp/doc/LISP.md: WARNING: document isn't included in any toctree
/home/chris/Documents/ChrysaLisp/doc/TAOS.md: WARNING: document isn't included in any toctree
/home/chris/Documents/ChrysaLisp/doc/TODO.md: WARNING: document isn't included in any toctree
done
preparing documents... WARNING: unsupported theme option 'vcs_pageview_mode' given
WARNING: unsupported theme option 'titles_only' given
WARNING: unsupported theme option 'includehidden' given
WARNING: unsupported theme option 'style_external_links' given
done
writing output... [100%] index                                                  
/home/chris/Documents/ChrysaLisp/doc/LISP.md: WARNING: Pygments lexer name u'ChrysaLisp' is not known
/home/chris/Documents/ChrysaLisp/doc/LISP.md: WARNING: Pygments lexer name u'ChrysaLisp' is not known
/home/chris/Documents/ChrysaLisp/doc/LISP.md: WARNING: Pygments lexer name u'ChrysaLisp' is not known
/home/chris/Documents/ChrysaLisp/doc/LISP.md: WARNING: Pygments lexer name u'ChrysaLisp' is not known
/home/chris/Documents/ChrysaLisp/doc/LISP.md: WARNING: Pygments lexer name u'ChrysaLisp' is not known
/home/chris/Documents/ChrysaLisp/doc/LISP.md: WARNING: Pygments lexer name u'ChrysaLisp' is not known
/home/chris/Documents/ChrysaLisp/doc/LISP.md: WARNING: Pygments lexer name u'ChrysaLisp' is not known
generating indices... genindex
writing additional pages... search
copying static files... WARNING: html_static_path entry u'/home/chris/Documents/ChrysaLisp/doc/_static' does not exist
done
copying extra files... done
dumping search index in English (code: en) ... done
dumping object inventory... done
build succeeded, 16 warnings.

The HTML pages are in _build/html.

**Comment by traverseda** [comment]
Ahh, yeah. Those theme errors can be ignored, or you can just comment them out in the conf.py file. They're used by the default theme, but everybody uses the much more readable "readthedocs" theme. They'd only get used if someone didn't install the readthedocs theme.

**Comment by vygr** [comment]
Hi Alex, I've installed on Ubuntu and Linux with:

pip install --user sphinx recommonmark sphinx_rtd_theme

But still don't get a usable index.html.

Chris

**Comment by vygr** [comment]
My ubuntu output from 'pip install --user sphinx recommonmark sphinx_rtd_theme'

chris@chris-VirtualBox-17:~/Documents/ChrysaLisp/doc$ pip install --user sphinx recommonmark sphinx_rtd_theme
Collecting sphinx
  Using cached Sphinx-1.7.2-py2.py3-none-any.whl
Collecting recommonmark
  Using cached recommonmark-0.4.0-py2.py3-none-any.whl
Collecting sphinx_rtd_theme
  Using cached sphinx_rtd_theme-0.2.4-py2.py3-none-any.whl
Collecting sphinxcontrib-websupport (from sphinx)
  Using cached sphinxcontrib_websupport-1.0.1-py2.py3-none-any.whl
Collecting babel!=2.0,>=1.3 (from sphinx)
  Using cached Babel-2.5.3-py2.py3-none-any.whl
Collecting imagesize (from sphinx)
  Using cached imagesize-1.0.0-py2.py3-none-any.whl
Collecting setuptools (from sphinx)
  Using cached setuptools-39.0.1-py2.py3-none-any.whl
Collecting packaging (from sphinx)
  Using cached packaging-17.1-py2.py3-none-any.whl
Collecting Pygments>=2.0 (from sphinx)
  Using cached Pygments-2.2.0-py2.py3-none-any.whl
Collecting requests>=2.0.0 (from sphinx)
  Using cached requests-2.18.4-py2.py3-none-any.whl
Collecting six>=1.5 (from sphinx)
  Using cached six-1.11.0-py2.py3-none-any.whl
Collecting docutils>=0.11 (from sphinx)
  Using cached docutils-0.14-py2-none-any.whl
Collecting typing; python_version < "3.5" (from sphinx)
  Using cached typing-3.6.4-py2-none-any.whl
Collecting alabaster<0.8,>=0.7 (from sphinx)
  Using cached alabaster-0.7.10-py2.py3-none-any.whl
Collecting Jinja2>=2.3 (from sphinx)
  Using cached Jinja2-2.10-py2.py3-none-any.whl
Collecting snowballstemmer>=1.1 (from sphinx)
  Using cached snowballstemmer-1.2.1-py2.py3-none-any.whl
Collecting commonmark<=0.5.4 (from recommonmark)
Collecting pytz>=0a (from babel!=2.0,>=1.3->sphinx)
  Using cached pytz-2018.3-py2.py3-none-any.whl
Collecting pyparsing>=2.0.2 (from packaging->sphinx)
  Using cached pyparsing-2.2.0-py2.py3-none-any.whl
Collecting idna<2.7,>=2.5 (from requests>=2.0.0->sphinx)
  Using cached idna-2.6-py2.py3-none-any.whl
Collecting urllib3<1.23,>=1.21.1 (from requests>=2.0.0->sphinx)
  Using cached urllib3-1.22-py2.py3-none-any.whl
Collecting certifi>=2017.4.17 (from requests>=2.0.0->sphinx)
  Using cached certifi-2018.1.18-py2.py3-none-any.whl
Collecting chardet<3.1.0,>=3.0.2 (from requests>=2.0.0->sphinx)
  Using cached chardet-3.0.4-py2.py3-none-any.whl
Collecting MarkupSafe>=0.23 (from Jinja2>=2.3->sphinx)
Installing collected packages: sphinxcontrib-websupport, pytz, babel, imagesize, setuptools, pyparsing, six, packaging, Pygments, idna, urllib3, certifi, chardet, requests, docutils, typing, alabaster, MarkupSafe, Jinja2, snowballstemmer, sphinx, commonmark, recommonmark, sphinx-rtd-theme
Successfully installed Jinja2-2.10 MarkupSafe-1.0 Pygments-2.2.0 alabaster-0.7.10 babel-2.5.3 certifi-2018.1.18 chardet-3.0.4 commonmark-0.5.4 docutils-0.14 idna-2.6 imagesize-1.0.0 packaging-17.1 pyparsing-2.2.0 pytz-2018.3 recommonmark-0.4.0 requests-2.18.4 setuptools-39.0.1 six-1.11.0 snowballstemmer-1.2.1 sphinx-1.7.2 sphinx-rtd-theme-0.2.4 sphinxcontrib-websupport-1.0.1 typing-3.6.4 urllib3-1.22

**Comment by traverseda** [comment]
I'll get that sorted out for you

**Comment by vygr** [comment]
No worries.

**Pull request closed without merging**
