### PR TITLE
Added a button to example

### PR DESCRIPTION
**Pull request by neauoire**
I’ve edited the comments to fit with the rest of the app, I would like to know how to bind a click event to the button so it changes the button background to red when I press it.

Cheers :)

### CODE REVIEW

**Comment by vygr** [comment]
Use (connect-button-click button id) to setup the event callback. I normally do these inside the UI-tree section. 

Then in the cond for the event do

(set button ‘color argb_red)
(view-dirty button)

Chris

—————-
Chris Hinsley

**Comment by neauoire** [comment]
That worked, using `(button-connect-click button id)`! 
Okay, I'm starting to get the hang of this.

I'll try build on this example and try to document this in the `TUTORIAL.md`

**Comment by neauoire** [comment]
How would I go about making a toggle flag, to switch from green/red.

I've tried storing a `toggle` value with: 

```
(defq toggle 0)
```

And on click I check for:
```
(set button 'color ((eq toggle 0) argb_green argb_red))
```

Any idea?

**Comment by vygr** [comment]
I'd do something like:

(defq toggle t)

then later on in the handler

(set button 'color (if (setq toggle (not toggle))) argb_green argb_red))

Chris

**Comment by vygr** [comment]
Also your structure can define multiple event ids.

(structure event 0
 (byte win_close)
 (byte click))

event_win_close would be 0
event_click would be 1
etc

**Comment by vygr** [comment]
I'll merge and do a quick tidy for you.

**Comment by neauoire** [comment]
Thanks a lot :)

**Pull request merged**
