### PR TITLE
Fixed some issues, added new and save

### PR DESCRIPTION
**Pull request by nuclearfall**
I'm sorry it's taken me so long to submit something.

For now, it still starts by opening a sample buffer to demonstrate an open file. but you can open new buffers and it stores previous buffers in a list for now. It would likely be more efficient to store them in a structure, using the paths and streams separately.

I tried to use a buffer structure. I'm not sure that I've done so in a way that is beneficial. I thought about using tuples with the path and the structure, but there are probably better ways of doing it.

I tried adding a textfield until I implement a modal or something of that sort, but I couldn't keep vdu from steeling/sharing focus. It was probably my implementation. 

I added a scrollbar to edit, slightly modifying your terminal code. It needs to go back to cursor x when a key is pressed, and manual movement doesn't adjust the scrollbar quite yet. It's something I can work on. 

The sticky x behavior is pretty universal across text interface. It might be something worth implementing in vdu, int the long run.

### CODE REVIEW

**Comment by vygr** [comment]
VDU probably was stealing the key events as the app is not checking the component-id matches before using the key event. The Mandelbrot demo is an example of what it should be doing, check the event target-id matches the component-id of the vdu widget prior to passing the key into the edit input.

Do you want to fix that first or shall I merge over ?

**Comment by vygr** [comment]
Tupple is ok for the textbuf structure IMHO, I just make sure to have a structure defined with the element offsets rather than use hard coded elements.

There is the ability to use (env) to create an isolated hash map way of doing this, then you could have named fields for things, but that's overkill when a Tupple will do fine.

If you're curious about that hash map idea, take a look at cmd/oops.lisp that I did for some experiments along these lines.

**Comment by vygr** [comment]
The Mandelbrot demo also gets you what you need to have the mouse click in the vdu area position the cursor !

You can use the rx, ry of the cursor click, plus the scroll offsets to figure out what to set the cx, cy to ! You will also need to know the vdu char width and heights, and you can see how to get that by looking at the gui/vdu/lisp.inc bindings. I'd add a new lisp function into that to return the char width and height tupple, and use it in your cursor click/drag/select positioning code.

**Comment by nuclearfall** [comment]
I'm curious about so much. :) 

I will fix the id issue. I also have a fix for the slider to ensure it moves along with manual cursor movement and that the scrollbar updates on manual offset adjustment. 

I will look at the oops.inc for guidance on hash maps, but will probably go ahead with the tuple here. 

It's funny, I was actually working on allowing clicking into the vdu when I saw your message. I was looking at freeball for guidance, but I'll take a look at mandlebrot as well.

**Comment by vygr** [comment]
In the Mandelbrot app.lisp you will see this clause.

((and (= id (component-get-id canvas))
						(= (get-long msg ev_msg_type) ev_type_mouse)
						(/= (get-int msg ev_msg_mouse_buttons) 0))
					;mouse click on the canvas view, zoom in/out, re-center

That is checking the id of the incoming GUI event matches the component id of the canvas, but you will want to check it matches the component id of the vdu widget, if it does then call the (edit-input) or let it drop through to the (t) clause that just passes it out to the GUI in general, ie your textfield and so forth.

**Comment by nuclearfall** [comment]
Yes, component-get-id is the method I was missing. I was trying to use component-connects on them and set a focus flag. It was silly.

I'm still not sure I entirely understand how structures are used here. Can you instance a structure something like (defq bob buffer) in some way? Am I properly using the structure as it is written?

If you were coding a structure for this, how would you define the offsets instead of hardcoding? Would you still need to refer to the oy as buffer_oy?

I thought of making a structure of buffer structures, but I'm don't know how I would access them.

**Comment by vygr** [comment]
If you look at apps/terminal/pipe.inc you will see I define a structure to name the element indexes of the pipe Tuple.

;pipe list element structure
(structure 'pipe 0
	(byte 'state 'select 'streams))

pipe_state is 0
pipe_select is 1
pipe_streams is 2

I then use (elem (const pipe_state) pipe) rather than (elem 0 pipe) to avoid hard coded element numbers.

**Comment by vygr** [comment]
A list of buffer Tuples is a perfectly good way of handling multiple buffers.

Structures are just equated offsets to things, they have no significance other than giving you a label/const_variable you can use for an element rather than a literal number.

The (structure) set of macros is in the gui/lisp.inc file if you want to take a look. It's just an easy way to define some variables based on the size of elements. Nothing sophisticated.

I don't believe in over sophistication, you might have noticed that ;)

**Comment by nuclearfall** [comment]
I really like that about this project. 

I see structures more clearly now. Most of my issue was conflating the structures and mail implementations utilizing them. My muddled thinking kept me in that pool for a bit.

**Comment by vygr** [comment]
On the subject of structures, the Lisp level (structure) helpers only bother to define variables you can use for offsets to things. The (def-struct) functions at the VP and C-Script level define some extra symbols prefixed with '_t_' to record the size/type of the element.

I will probably make the (structure) macros do the same thing eventually, just have not needed it yet. And I only bother doing something if I actually need to use it or see others needing to use it.

**Comment by nuclearfall** [comment]
I think the offsets are fine. Just not what I typically think of as a structure. I'm taking notes for a beginner's tutorial. ;)

**Comment by vygr** [comment]
Ultimately that's all structure declarations are.

They are a way to define some labels or equates that are offsets from a pointer to the start of an instance of said structure to the elements of that structure. Often with some extra info like the `_t_` prefixed equates in case you want to write some code that automatically knows what the size/type of the element is.

Wrap it up in whatever syntax or buzzwords/keywords you want, it's still just avoiding hard coded numbers for some names.

**Pull request closed without merging**
