### PR TITLE
Initial command argument type validation

### PR DESCRIPTION
**Pull request by FrankC01**
Adds fundamental type validation.

Integer and real validation still pending but putting the change in now to provide early value.

### CODE REVIEW

**Comment by vygr** [comment]
I would be very tempted to define def: symbols with a trailing : as our standard ?

(def: ‘(a: b:))

I think that would aid readability and make them stand out as keys/keywords?

**Comment by vygr** [comment]
Prefix or trailing it way more readable.

**Comment by FrankC01** [comment]
I am 100% with creating keywords with a trailing ':'

I also consider keywords are a 'type' of symbol

**Comment by vygr** [comment]
Just looked up the Lisp standard for keywords and it’s a : prefix so let’s go with that to keep in line with Lisp style.

**Comment by FrankC01** [comment]
Will do

**Comment by vygr** [comment]
I just push a change to repl_eval that always self evaluates any symbol prefixed with :.

So you don't require the (def:) anymore, and these : symbols will evaluate faster than the old (def:) self eval symbols.

Do a 'make boot' let me know what you think.

**Pull request closed without merging**
