### PR TITLE
Updates to argparse and docs

### PR DESCRIPTION
**Pull request by FrankC01**
Added better integer validation (pos only or any)

### CODE REVIEW

**Comment by vygr** [comment]
Just a few  minor comments.

```lisp
    (defun-bind generate-cmd-help (lst)
      (defq _eat_chunk "")
      (defun _eat (_x)
        (setq _eat_chunk (cat _eat_chunk (wrap-block _x))))
      (each (lambda (el)
              (setq _eat_chunk (cat _eat_chunk (str "## " (first el))))
              (pipe-run (second el) _eat)) lst)
      (save "" target)
      (save _eat_chunk target))
```

No need to do the (save "" target), the next line will overwright that file again.

More interesting might be, that this code is (cat) over and over onto _eat_chunck which works, but its bad on memory copying. Each time the cat happens it has to allocate a new memory chunck and copy the two halves over and then free the old chucnk.

If you just collect the chunck into a _eat_chunk_list starting off with (list) or some initial value, I'm sure you'd have some funcky (reduce) probably. And then only on the save do:

```lisp
(save (apply cat _eat_chunk_list) target)
```

That will end up with 1 single allocation and a copy per chucnk, then a single memory free.

Regards

Chris

**Comment by vygr** [comment]
You could probably end up with it as a single:

```lisp
(save (apply cat (reduce (lambda (clst filename) (push clst (pipe-run .....))) lst (list))
```
etc

**Comment by FrankC01** [comment]
I could but I tend to stay away from APL like 'A calculator in 1 line' in open source for readability and maintenance. Also, I'm a big fan of small pure functions that can be chained (composed) together in various ways.

**Comment by vygr** [comment]
It's all good. But the issue with the use of cat is still worth using a list of chunks...

I'm finding your more pure functional style code very interesting to read, given me thoughts on where I can improve my code.

**Comment by FrankC01** [comment]
I'll open an issue with 'refine command make docs' so as not to lose track of it

**Pull request merged**
