### PR TITLE
lisp.lisp, command prompts, and print abstraction

### PR DESCRIPTION
**Pull request by nuclearfall**
So, there are a few things in here.

EDIT: This has stopped lisp from displaying the ChrysaLisp message altogether. Probably not a reasonable fix.
~~Piping `echo (+2 4) | lisp` no longer brings up the Lisp interpreter prompt.~~

I made a definitions for the enter key and a function to display the command prompt (with or without a trailing CR). A broader any_key(num) might be a better long term option than just an enterkey defintion, but I was drowsy last night and didn't know if it would be of much use in the long run.

I've also come up with abstract print function apr(c) that can replace existing print functions on the frontend to make programming flexible text printing more of a thing.  I'm not sure where you would want to put it, or if it's even as useful as I think it might be, so I just left it in terminal app.lisp for you to decide.

### CODE REVIEW

**Comment by vygr** [comment]
On the abstract print idea, the mechanism used elsewhere has been to standardise on code useing the (print) function, and then code that wish can redirect this by defining their own (print) function...

Have a look at this in the class/lisp/compile.lisp file. The assembler child process redirects the assemblers normal use of (print) to write to a out-stream rather that stdout, which is what the boot.inc file (print) does. I'd use the same idea here.

**Comment by vygr** [comment]
I noted on another comment that I was going to do the work to change the TUI to use the same line buffer code as the GUI, might be best to wait till I have that sorted out.

I like the idea to abstract the terminal prompt, eventually that can then do nice things like print the user name or current directory or such.

The define for enter_key (ascii-code 10) would be better done as a macro ! Take a look at the one I use in apps/chess/child.lisp (LF), that ends up with no extra environment lookup at runtime. Although this is not really time critical code, but it's worth thinking about what the difference is if you've not come across Lisp macro before. The (const) is actually just a macro that does read time evaluation and the result is what happens at runtime, so (const (ascii-char 10)), turns into an embedded "\n" in your code.

**Comment by nuclearfall** [comment]
Well, this was a huge mess. I think I must've done add *. Sorry about that.

This all sounds like stuff I should be taking a look at. I will add macros to the list as well.

**Comment by vygr** [comment]
Hey your changes inspired me to hack on the GUI terminal over the weekend ! :)

The latest repo has your wallpaper.tga 24bit working now and greyscale import working while I was in that bit of code...

So your definitely having an effect :)

Regards

Chris

**Pull request closed without merging**
