### PR TITLE
More commands

### PR DESCRIPTION
**Pull request by FrankC01**
Tweaked argparse and added 'head' command

### CODE REVIEW

**Comment by vygr** [comment]
What I think we need as far as autogening the cmd/ docs is to get the 'make docs' commands to run every command in the cmd/ folder with the -h option, capture the output and build a docs/CMD.md file.

There is a (pipe-run) commands I added to apps/terminal/pipe.inc a way back that  might come in handy here, may need some modification to capture the output etc, but it's would be a reasonable plane to do it this way rather than scan the text of the files. ?

**Comment by FrankC01** [comment]
I had that very question, how to run a command within a command and pipe the child stdout to current stdin...

**Comment by vygr** [comment]
Take a look at that (pipe-run) function, maybe take it and improve it somewhat. It was a quick hack at the time.

**Comment by FrankC01** [comment]
Will do

**Pull request merged**
