### PR TITLE
Preview first draft of host GUI for framebuffer

### PR DESCRIPTION
**Pull request by ghaerr**
Hello @vygr,

This is a very rough first draft of the new host GUI routines for framebuffer (and SDL), along with a test harness program (`fbtest.c`). I kind of ran out of time trying to get this all written in one day.

There are all sorts of things wrong with this at the moment, and this PR is only meant to give you a preview for comments, not to be committed. I have not even attempted linking with CL yet, and the files are currently all in a completely seperate `gfx/` directory for the time being. The files are also in C, with .cpp coming, due to some linkage issues I'm having.

The `gfx/Makefile` will make two programs (`fbtest-sdl` and `fbtest-fb`) on Linux (and only the SDL version on macOS). The framebuffer test has only tested on RPi, and it works, although it still has some problems. I ended up spending lots of time getting the event code working for both mouse and keyboard, and dummying up the events to look like SDL. These will definitely need enhancing depending on exactly what fields CL looks at from SDL events.

The `fbtest-{sdl,fb}` program is a very crude terminal emulator that just draws graphically on the SDL or framebuffer canvas from keystrokes, by drawing bits from an 8x16 ROM. I happened to have that program written for SDL, so I hacked it into using the new CL host GUI API. I thought it best to try to get the event system running before trying to integrate with CL, as I didn't want to just boot CL and have it fail miserably without knowing what was happening.

Currently, texture drawing is completely untested, and all blits are SRCCOPY only, with no color mods. The code relies on the framebuffer being ARGB (32bpp), but I will add full conversion blits and blend blits after getting a few more things working. Also, the RPi console is currently interfering with the framebuffer, that is, if anything is written to stdout, the console takes over the framebuffer again and disrupts the graphics.

The framebuffer backbuffer is not yet implemented, all drawing is direct to the hardware FB. DrawRect and FillRect are coming shortly. I haven't stated on clipping yet. I can possibly get those done tomorrow.

I'll talk with you on Element in the morning.

Thank you!

### CODE REVIEW

**Comment by vygr** [comment]
Thank you ! And thanks for getting involved both here and in the Element chat room :)

**Comment by vygr** [comment]
Sorry I change out the func table names on your today, but you did provoke it :)

```C++
void (*host_gui_funcs[]) = {
	(void*)host_gui_init,
	(void*)host_gui_deinit,
	(void*)host_gui_box,
	(void*)host_gui_filled_box,
	(void*)host_gui_blit,
	(void*)host_gui_set_clip,
	(void*)host_gui_set_color,
	(void*)host_gui_set_texture_color,
	(void*)host_gui_destroy_texture,
	(void*)host_gui_create_texture,
	(void*)host_gui_begin_composite,
	(void*)host_gui_end_composite,
	(void*)host_gui_flush,
	(void*)host_gui_resize,
	(void*)host_gui_poll_event,
};
```

**Comment by ghaerr** [comment]
All host GUI functions are implemented for framebuffer, with the exception of alpha blending when drawing textures. Currently alpha is ignored and always effectively 255. I've been testing new clipping code with each of the drawing functions, and all drawing is now clipped to the framebuffer or as specified in `SetClip` (host_gui_set_clip) so we should be good for CL. The event loop is running well for keyboard and mouse input, but still only testing with the test harness. Tomorrow I hope to hook everything up and run CL on framebuffer for the first time!

There's still a few structure and types/naming issues to sort out. I'm aiming to use only our own structures (e.g. `Rect`, `Drawable`, `Texture` and `Event`) instead of the `SDL_` equivalents in both the `gr-sdl.cpp` and `gr-fb.cpp` files but its gotten a bit complicated with the SDL_Event structure. It would be nice to use these typedefs rather than `uint64_t` or `void *` which are very generic and prone to error within the driver files. This can be sorted out once CL actually runs on FB.

**Comment by ghaerr** [comment]
Closing this PR as it is being replaced by #272.

**Pull request closed without merging**
