### PR TITLE
Small bugs

### PR DESCRIPTION
**Pull request by nuclearfall**
Just learning Lisp and this is my first push request, so pardon if I make a mistake. 

Window for images was too small—maybe only on my screen? Also, bug fix in terminal window where backspace deletes prompt. The left and right arrows on my keyboard output P and O, but I'll save that for next time.

### CODE REVIEW

**Comment by vygr** [comment]
The image loading demo does actually start with a smallish window size. Even 400x400 would still be too small for some and too big for others. What would be best would be resize the window to fit the loaded image, which I will probably do after your merge. 

On the terminal, yes should fix the issue, how about the same fix for the tui version of the terminal too in tui.lisp :) it has the same issue.

Pop that extra Tui fix in and I’ll merge over the three fixes together. 

Regards 

Chris

**Comment by vygr** [comment]
Quick question. You did notice that you can resize the demo apps by dragging on the window borders ?

Just in case that wasn’t obvious.

**Comment by vygr** [comment]
I just noticed that the tui version of that backspace bug only effects the Windows tui ! So I'll fix that once I get to my Windows laptop again.

Merge your change over now.

**Comment by nuclearfall** [comment]
Sorry, the family came home and I got distracted.

For some reason I was thinking the images in the image viewer were all the same size. You're right a dynamic resize would be better. 

I will be reading through the code in the next few days. Hopefully, I can help out some more. I really love the idea behind the project.

**Comment by vygr** [comment]
Thank you, I'm happy to have sparked your interest and gained your input :)

I was going to do this over the weekend here :) I'll fix that and you can think on the new Terminal  app ;)

**Pull request merged**
