### PR TITLE
sync to original repo

### PR DESCRIPTION
**Pull request by BananaEarwig**

### CODE REVIEW

**Comment by vygr** [comment]
Martyn, this should be a PR to the Windows branch !

**Comment by vygr** [comment]
I'll merge master over to the Windows branch so you get the up to date stuff. Could you pull it after I do that and PR from that branch with your extra's. I don't want to risk change the master branch just yet.

Ta

**Comment by vygr** [comment]
Updated Windows from Master, so they should both be identical for now.

**Comment by vygr** [comment]
Martyn, might be easiest this time, to just drop me a .zip here of your files. I'll sort out the Windows branch and make sure everything compiles at my end, and then push them. You can then clone down a nice fresh set ?

**Comment by BananaEarwig** [comment]
Yeh sorry...I blame jetlag :)

**Comment by BananaEarwig** [comment]
Latest version of windows support files. requires manually created platform and arch files and windows bins for sdl etc 
[windows.zip](https://github.com/vygr/ChrysaLisp/files/2893900/windows.zip)

**Comment by vygr** [comment]
Close this pull request. Will get your zip merged in to Windows branch soon.

**Pull request closed without merging**
